### ISSUE TITLE
Variant annotation test data alignment

### ISSUE THREAD

**Issue by david4096** [ga4gh/compliance#139]
@sarahhunt has put together some preliminary tests for the variant annotation API. These tests need to be aligned to the test data Pablo is using on the reference server.

For example, currently tests against data not in the existing compliance test data.

        final String alternateBases = "G";
        final String impact     = "MODERATE";
        final String featureId  = "NM_001005484.1";
        final String hgvsc      = "NM_001005484.1:c.451A>G";
        final String hgvsp      = "NM_001005484.1:p.Ser151Gly";
        final int cdnaStart     = 450;
        final int cdsStart      = 450;
        final int proteinStart  = 150;

Need to identify which transcript effects to test against.

**Comment by sarahhunt** [comment]
The variant annotation compliance tests use WASH7P_annotation.vcf and OR4F_annotation.vcf which were taken from Pablo's server test data file 1.ann.vcf.gz. 

The WASH7P file contains multiple transcripts, so it used for testing filtering by transcript; the ORAF file has only one transcript, so is used for checking specific values in the TranscriptEffect record, as above. Different test sets are used to separate filter failures from other wrong-value failures.

**Comment by david4096** [comment]
Closed with #168
