### ISSUE TITLE
Update CallsetsSearchResponseCheckIT to allow for VariantSet without CallSets

### ISSUE THREAD

**Issue by sarahhunt** [ga4gh/compliance#145]
The test searchForExpectedCallSets assumes all VariantSets have CallSets, which is not required by the schema and no longer the case.

The opposite check, that a VariantSetId listed in a CallSet returned data, would be valid.

**Comment by david4096** [comment]
Great! For this test I've modified it so that we are checking the variantSetId field of returned callsets only when some callSets have been returned. The test you've suggested, to find VariantSets by the data retrieved from a callset should also be there, I'll put it in another issue.
