### ISSUE TITLE
Test all read groups in a set search

### ISSUE THREAD

**Issue by david4096** [ga4gh/compliance#184]
The current tests for reads search could be amended to cover the case when all the readgroups within an individual BAM are being searched.

[This test](https://github.com/ga4gh/compliance/blob/master/cts-java/src/test/java/org/ga4gh/cts/api/reads/ReadsSearchIT.java#L185) checks across readgroupsets. Creating another test like this one that limits to only searching within a single readgroupset would demonstrate a useful feature.

**Comment by dcolligan** [comment]
Fixed in #185
