### ISSUE TITLE
Status code for no IDs: readSearch

### ISSUE THREAD

**Issue by david4096** [ga4gh/compliance#187]
In SearchReads the expected status code for a request with no readgroupids is currently 501, not implemented. However the signature was changed in the reference server to return a 400. Which is correct?

`[TESTLOG] FAILED searchReadsWithNoIdsFails(org.ga4gh.cts.api.reads.ReadsSearchIT) due to expected:<[501]> but was:<[400]>`

**Comment by diekhans** [comment]
SearchReadsRequest indicates that "The ReadGroups to search. At least one id must be specified."
so 400 is correct.

**Comment by jeromekelleher** [comment]
Agreed, 400 is correct.
