### ISSUE TITLE
compliance_redux: mvn install fails

### ISSUE THREAD

**Issue by calbach** [ga4gh/compliance#28]
Hi all, I didn't want to add noise to the PR thread. I've cloned this branch and I'm unable to build it locally.

```
compliance(compliance_redux)$ mvn install

[INFO] Scanning for projects...
Downloading: http://repo1.maven.org/maven2/org/springframework/spring-framework-bom/4.2.0.RC2/spring-framework-bom-4.2.0.RC2.pom
[INFO] Unable to find resource 'org.springframework:spring-framework-bom:pom:4.2.0.RC2' in repository central (http://repo1.maven.org/maven2)
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).


Project ID: org.springframework:spring-framework-bom

Reason: POM 'org.springframework:spring-framework-bom' not found in repository: Unable to download the artifact from any repository

  org.springframework:spring-framework-bom:pom:4.2.0.RC2

from the specified remote repositories:
  central (http://repo1.maven.org/maven2)

 for project org.springframework:spring-framework-bom
```

**Comment by hjellinek** [comment]
Hi @calbach, we haven't seen that one before.  Inability to pull in a copy of the Spring framework could simply be a transient problem with that Maven repo.  That said, it appears you are working with a version of the code that predates some unrelated-but-important Maven tweaks I checked in.  I recommend you pull the code in the PR again, clean out the GA4GH portion of your local Maven repo _just this once_, and try building again.

```
$ rm -r ~/.m2/repository/org/ga4gh/
$ mvn clean install
```
Let us know how it goes.

**Comment by calbach** [comment]
Thanks @hjellinek, this does not work for me as of the current compliance_redux branch.

As of an hour ago I've temporarily sidestepped this by switching from Linux to my Mac in my attempts to run the compliance suite. I've finally gotten it to build there, at least, so I'll circle back to this issue once I've assessed the actual output of the test suite.

**Comment by calbach** [comment]
Upgrading to mvn 3.3.3 resolved the issue.

**Comment by diekhans** [comment]
Can we add an explicit check for maven version?

In general, I am less than impress with the usability and
lack of flexibility of maven.  Wayne likes Gradle much better,
but the decisions was made to use Maven because schema used
it.

I am a bit regretting that situation and wonder if switch
schema to Gradel would have been a better choice.

Any more informed opinions?

**Comment by hjellinek** [comment]
There's a bit of a bootstrapping problem in checking the Maven version, as we'd either have to add a script to do it or somehow convince Maven to.  I prefer Gradle too, but switching to Gradle right now would be a major disruption.

I'd be up for experimenting with it later, but I expect we'll find annoyances in any build tool we use.  Even with Gradle, we'd use the so-called "Maven" package repositories for library dependencies, and they can be a source of transient errors all by themselves.

For now, the simplest approach is documentation.  This is one for the quickstart guide.

**Comment by diekhans** [comment]
Herb Jellinek <notifications@github.com> writes:
> I prefer Gradle too, but switching to Gradle right now would
> be a major disruption.

that is a long-term thing to think about

> For now, the simplest approach is documentation. This is one for the quickstart
> guide.

absolutely

**Comment by fnothaft** [comment]
> There's a bit of a bootstrapping problem in checking the Maven version, as we'd either have to add a script to do it or somehow convince Maven to. I prefer Gradle too, but switching to Gradle right now would be a major disruption.

There's a maven plugin that does all this. E.g., here's what we do in ADAM for the check:

```
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-enforcer-plugin</artifactId>
          <version>1.3.1</version>
          <executions>
            <execution>
              <id>enforce-versions</id>
              <goals>
                <goal>enforce</goal>
              </goals>
              <configuration>
                <rules>
                  <requireMavenVersion>
                    <version>[3.1.1,)</version>
                    <message>ADAM requires Maven 3.1.1 or greater</message>
                  </requireMavenVersion>
                  <requireJavaVersion>
                    <version>[1.7,)</version>
                    <message>ADAM requires Java 1.7 or greater</message>
                  </requireJavaVersion>
                </rules>
              </configuration>
            </execution>
          </executions>
        </plugin>
```

**Comment by hjellinek** [comment]
Thanks @fnothaft.  We should use the Maven Enforcer plug-in for this.  I opened #45 to cover this.
