### ISSUE TITLE
compliance_redux: update version number in POMs from 0.5.1-SNAPSHOT

### ISSUE THREAD

**Issue by hjellinek** [ga4gh/compliance#31]
All of the `pom.xml` files that mention a version mention "`0.5.1-SNAPSHOT`".  We will need to change that, though I don't know what the new version will be yet.

**Comment by diekhans** [comment]
Is it possible to have this in one file?  oh, XML entities ... never
mind

**Comment by hjellinek** [comment]
Surprisingly, I believe it is possible: `parent/pom.xml`, in the `<properties>` section.  We _may_ be able to get Maven to use `${ga4gh.schema.local.version}` in the other places the string appears now.

    <properties>
        <ga4gh.schema.local.version>0.5.1-SNAPSHOT</ga4gh.schema.local.version>
        ...
    </properties>
