### ISSUE TITLE
complaince tests should not assume verion number is part of URL

### ISSUE THREAD

**Issue by diekhans** [ga4gh/compliance#35]
From: Jerome Kelleher
One immediate problem I had was that the kit automatically appends "v0.5.1" to the URL
provided. URL versioning isn't part of the API. Implementers are free to have whatever URL
prefix they like, but this should be supplied as part of the URL argument. Because of this, I
wasn't able to get much of a sense of what's happening test-wise.

I

**Comment by hjellinek** [comment]
The URL is normally passed via the command line, and none of the implementation assumed the version number as part of the URL.  But I did change all the baked-in URLs in config and doc files to remove all vestiges, to avoid confusing people.

Fixed in 4bc35c8b8db3c10e1eaca1911d2741059f4668a3.
