### ISSUE TITLE
compliance_redux: configuration of server URL

### ISSUE THREAD

**Issue by sarahhunt** [ga4gh/compliance#40]
Following instructions on how to run the compliance tests (thanks @hjellinek! ) I'm finding the URL configured in parent/pom.xml is not used when running the tests under maven. It there somewhere else this neede to be confugured too?  

Details: 

1) parent/pom.xml edited to use: <ctk.tgt.urlRoot>http://localhost:3000/ga4gh

2) mvn clean install

messages use default server URL::

[main] INFO org.ga4gh.ctk.transport.avrojson.AvroJson - create interaction for http://localhost:8000/v0.5.1/datasets/search SearchDatasetsRequest SearchDatasetsResponse

The build appears to be successful

3)  mvn test failsafe:integration-test

default URL used again:

[main] INFO org.ga4gh.ctk.transport.avrojson.AvroJson - create interaction for http://localhost:8000/v0.5.1/variantsets/search SearchVariantSetsRequest SearchVariantSetsResponse
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.009 sec <<< FAILURE! - in org.ga4gh.cts.api.variants.VariantsSearchIT

**Comment by hjellinek** [comment]
Leaving aside for now the question of why the value in the POM is not used, the file `ConfigTheCTK.md` suggests a workaround:

```
mvn -Dctk.tgt.urlRoot=http://localhost:3000/ga4gh -Dcfg.tgt.dataset_id=my_dataset_id clean install
```

**Comment by hjellinek** [comment]
If you want to run with or without bothering to build everything, you can do this:

```bash
$ ./ctk --ctk.tgt.urlRoot=http://localhost:3000/ga4gh --cfg.tgt.dataset_id=my_dataset_id
```
