### ISSUE TITLE
Problems in RunningTests_CLI.md

### ISSUE THREAD

**Issue by hjellinek** [ga4gh/compliance#43]
From @calbach:

... a few issues in the [detailed installation section](https://github.com/ga4gh/compliance/blob/compliance_redux/docs/RunningTests_CLI.md#details):
- Ideally most of these steps should be eliminated or wrapped up into a helper script. If they cannot be eliminated for the time being, textual descriptions such as "Create a directory target for the test reports to go into.", should be replaced with an actual command line.
- `jar xf ctk-cli-0.5.1-SNAPSHOT.jar antRunTests.xml` produced nothing for me - I had to copy the version from ctk-server/lib
- `chmod +c` should probably be `chmod +x`

**Comment by hjellinek** [comment]
Given that this contains a section entitled "Quickstart" which covers running the `ctk` script (though it doesn't discuss writing tests at all), it should be merged with the Quickstart document of @macieksmuga's, or discarded.  Assigning to @macieksmuga.

**Comment by macieksmuga** [comment]
Resolved via PR #72
