### ISSUE TITLE
make version easy to parse out of compliance dataset names

### ISSUE THREAD

**Issue by diekhans** [ga4gh/compliance#50]
"compliance-dataset1" is tricky if you want to parse the version out of it (e.g. sorting for finding the newest),  suggest ga4ga-compliance-dataset-1 or something else that is easy to just split rather
than a regexp.

**Comment by hjellinek** [comment]
Assigning to @macieksmuga first, since he's creating a new test dataset and will of course have to name it.  Maciek, please reassign to @hjellinek afterwards to make the corresponding code changes.

**Comment by macieksmuga** [comment]
I feel we shouldn't be naming the compliance dataset anything - since it's part of the compliance suite, we can use the git name for the commit it comes from. If @hjellinek and @diekhans agree with this, I'll close this issue.
