### ISSUE TITLE
Read tests in variants package

### ISSUE THREAD

**Issue by sarahhunt** [ga4gh/compliance#51]
The HTML report for org.ga4gh.cts.api.variants.CallsetsSearchResponseCheckIT is reporting checkSearchRouting errors for reads,readgroupsets and references

Are there a few missplaced or unneccessary makeUrl calls in:

cts-java/src/test/java/org/ga4gh/cts/api/variants/CallsetsSearchResponseCheckIT.java

**Comment by hjellinek** [comment]
That may be a matter of opinion: though the schemas don't define them, we do make use of HTTP response codes to signal the success or failure of API calls.  There are some tests in `CallsetsSearchResponseCheckIT` that check server endpoint responses to various types of calls (`POST`, `GET`, `OPTIONS`). 

If you're specifically referring to the unused variable `allSearchUrls`, it's there for future expansion purposes, but I wouldn't say it's unnecessary.

Perhaps I'm not understanding the issue you're raising.  Can you can restate it in terms of what you're expecting to see, and what you did see?

**Comment by calbach** [comment]
The issue is that the test is named CallsetsSearchResponseCheckIT, but tests unrelated functionality i.e. hitting reads, readGroupSets, and references endpoints.

**Comment by sarahhunt** [comment]
Precisely - thanks @calbach! 
It's a good idea to separate the tests for different parts of the schema into different packages, so groups serving only reads or only variants can test without the noise, but it does need to be done cleanly.

**Comment by hjellinek** [comment]
Acknowledged.  This class is a bit of a hodge-podge, including as it does a version of one of the old JavaScript-based tests, plus low-level HTTP tests, plus other tests - related and not so related.  That description applies to many of the other test classes, too.

I consider the current batch of tests as conversation-starters and as a source for code snippets, not as holy writ.  I expect we'll replace most or all of the current tests, and I hope we'll be able to do that quickly.

Any volunteers to restructure this class?
