### ISSUE TITLE
Reference tests should not use 'TODO' for the md5checksum

### ISSUE THREAD

**Issue by calbach** [ga4gh/compliance#54]
I'm not sure I understand how this is passing for the reference server, if it is.

https://github.com/ga4gh/compliance/blob/compliance_redux/cts-java/src/test/java/org/ga4gh/cts/api/references/ReferencesSearchIT.java#L50
https://github.com/ga4gh/compliance/blob/compliance_redux/cts-java/src/test/java/org/ga4gh/cts/api/references/ReferenceBasesSearchIT.java#L73

The Google Genomics API returns a 400 error, because this is not a valid hexadecimal string.

**Comment by hjellinek** [comment]
Yes, that's a test that's aimed squarely at the ref server right now.

It's also not appropriate to the test data currently provided with the CTK.

Both will change (along with the ref server's MD5 handling :-)) soon.

**Comment by macieksmuga** [comment]
This is now a [server issue](https://github.com/ga4gh/server/issues/540).
