### ISSUE TITLE
Tests presume too much about readGroupId assignment

### ISSUE THREAD

**Issue by calbach** [ga4gh/compliance#55]
This is related to https://github.com/ga4gh/schemas/issues/381

Currently the tests appear to require that IDs be assigned in the following form, which is presumably the behavior of the reference server:
`datasetName(or ID?):sampleName(?):readGroupName(?)`

We either need to clarify the documentation on `ReadGroup.name` and/or `ReadGroup.id` as to how it relates to the read group ID which comes off a sequencer, *or* we need to describe in the test-data section how it expects read group names to be assigned upon import. Though the docs are especially murky on `ReadGroup.id`, it should follow the pattern of our other resource IDs and the client should not assume that they have control over the value.

The integration test should use SearchReadGroupSets() to acquire the actual ReadGroupIds for later use in testing SearchReads.

**Comment by hjellinek** [comment]
I think this has been fixed in the course of other updates to `compliance_redux`.  If not, please reopen and include the class and method names that are still making these assumptions.
