### ISSUE TITLE
checkComplianceDatasetIsPresent ordering assumption

### ISSUE THREAD

**Issue by sarahhunt** [ga4gh/compliance#70]
Hi @hjellinek ! 

I've picked up the latest version of the compliance suite after the recent flurry of activity and run it against my dev server which has post v0.5.1 features.

The checkComplianceDatasetIsPresent test in DatasetsSearchIT.java is failing for me because it expects the compliance dataset to be the first returned, when we currently return it as the third record. It would be better to loop through the returned datasets than assume ordering.

**Comment by hjellinek** [comment]
Hi @sarahhunt!  Right you are, and jealous I am of you with your multiple datasets.  I will update this test -- though I may need you to test it for me.  I believe that @macieksmuga is working on adding a second capital-D Dataset to the Compliance data.

**Comment by hjellinek** [comment]
@sarahhunt, please test it and reopen the issue if not fixed.
