### ISSUE TITLE
'endpoints' tests do not appear to have any basis in the ga4gh/schemas spec

### ISSUE THREAD

**Issue by calbach** [ga4gh/compliance#88]
These tests look to be written based on specific implementation details of the reference server, I would not expect them to pass on any other implementation. For example, a GET request to /callsets/search is interpreted by the Google API as a request for a callset with id 'search'.

To me, these looks more like server integration tests which I would expect to live in the reference server repository, if anywhere.

**Comment by jeromekelleher** [comment]
I agree with @calbach on this example. What are the tests checking for?

**Comment by hjellinek** [comment]
At @jeromekelleher's suggestion, I pared down the tests to a single one that checks the response to malformed POST payloads sent to search methods.

The one other useful test had been checking the response to `OPTIONS`, `GET`, and `POST` methods.  Arguably the schemas should specify the correct response to OPTIONS, at least, and test for it.

**Comment by hjellinek** [comment]
Closed pending merge.
