### ISSUE TITLE
Tests should distinguish between absence of end point and lack of data

### ISSUE THREAD

**Issue by sarahhunt** [ga4gh/compliance#89]
Minor issue - we have not implemented the reads API but have 3 reads tests passing as the missing endpoints return 404 errors.

This will have to wait until exception handling is fully agreed and documented, but the tests should distinguish between absence of endpoint and lack of data.

**Comment by jeromekelleher** [comment]
I think the correct behavior for a server here should be a HTTP 501 (Not Implemented) @sarahhunt. I'm not sure how we should structure the compliance tests, but the basic idea would be that the server gets low score for 404ing a POST search endpoint like ``/variants/search``, and a slightly better score for returning a 501 telling the client that the end point is not implemented. A server cannot be fully compliant if it doesn't implement all of the API, but it is better to 501 for a missing piece of functionality that to give any other error.

Does this sound sensible to you @calbach?

**Comment by calbach** [comment]
Yep, definitely agree. 501 is clearest.

**Comment by sarahhunt** [comment]
Returning 501 for non-implemented endpoints sounds fine to me.

I can see it being a feature servers are often not compliant with - for example, a group with only reads data may not have time to monitor and update their code when new G2P endpoints they don't have data to support enter the release branch.

**Comment by calbach** [comment]
I think we're in agreement and there's nothing left to be done here so I'm closing. Please reopen if you disagree.
